### ISSUE TITLE
base_local_plannerの解説で移動ロボットの座標系があったほうが親切

### ISSUE THREAD

**Issue by n-ando** [robo-marc/navigation_documents#2]
base_local_plannerの解説で、移動ロボットの直進方向がX軸との記述があるが、本ドキュメントはロボットの専門家ではないソフトウェア技術者が読むことを前提としているので、あらかじめ座標系の定義などを追加しておいた方が良い。

**Comment by sec-matsumoto** [comment]
7.2 座標系に座標系の解説を追加し、3章からリンクをたどれるようにしました。
