### ISSUE TITLE
用語「ストラフ」は適当か

### ISSUE THREAD

**Issue by n-ando** [robo-marc/navigation_documents#5]
ストラフ移動という用語は聞いたことがありません。これはどこから出てきたどこから出てきた用語でしょうか？

strafe は発音的には「ストライフ（ストレイフ）」のようです。
また、縦横移動に関しては、あえて記述すると

- 縦移動: longitudinal movement
- 横移動: lateral movement
- 斜め移動: diagonal movement
- 回転移動: rotational movement
- その場回転（超信地旋回）: spin turn

となるでしょうか？ストラフ（ストライフ）に関しては、横移動とした方が良いように思います。

**Comment by sec-matsumoto** [comment]
「横移動」に修正いたしました。
