### ISSUE TITLE
新規作成した図はPPT形式でも保存

### ISSUE THREAD

**Issue by n-ando** [robo-marc/navigation_documents#6]
新規作成した図はPPT形式でもリポジトリに入れておいて
また、引用した図の元は、元ドキュメント内にコメントとして入れておいていただけると助かります。

**Comment by sec-matsumoto** [comment]
新規作成した図の元データをimagesディレクトリに格納しました。
引用図の引用表記は、現在対応中です。

**Comment by sec-matsumoto** [comment]
引用図の引用表記についても、対応完了しました。
