### ISSUE TITLE
図のアスペクト比を固定にしてください

### ISSUE THREAD

**Issue by n-ando** [robo-marc/navigation_documents#7]
ドキュメント中の図が、ブラウザの横幅によってアスペクト比が変更される形式で添付されているようなので、アスペクト比が変わらない形式で張り付けてください。

**Comment by sec-matsumoto** [comment]
アスペクト比が固定されるように修正いたしました。
rst内のimageディレクティブで、widthのみを指定することで、固定されるようになっています。

**Comment by n-ando** [comment]
クローズします。
